# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_date'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify_date'),
        ),
    ]
